"""empty message

Revision ID: d52b34be6459
Revises:
Create Date: 2024-01-28 18:50:22.692339

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d52b34be6459"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cleaning",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("chat", sa.String(), nullable=False),
        sa.Column("cleaned_chat", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
        sa.UniqueConstraint("uuid", name="uuid_unique_constraint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cleaning")
